(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const panels=$$('.report-panel'),tabs=$$('#kazalo [role=tab]'),nav=$('#kazalo'),menu=$('.mobile-menu');let keyboardTab=null;
document.body.classList.add('tabs-ready');
function show(id){if(!panels.some(p=>p.id===id))id=panels[0].id;panels.forEach(p=>p.hidden=p.id!==id);tabs.forEach(t=>{const active=t.getAttribute('aria-controls')===id;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;});window.dispatchEvent(new Event('resize'));}
function reveal(hash,scroll=true){let id;try{id=decodeURIComponent((hash||'').replace(/^#/,''));}catch{return;}const el=document.getElementById(id);const p=el?.closest('.report-panel');show(p?.id||'zavihek-pregled');if(el){let parent=el.parentElement;while(parent){if(parent.tagName==='DETAILS')parent.open=true;parent=parent.parentElement;}if(scroll)requestAnimationFrame(()=>el.scrollIntoView({block:'start',behavior:'instant'}));}}
function go(hash){if(location.hash===hash)reveal(hash);else location.hash=hash;}
window.addEventListener('hashchange',()=>{reveal(location.hash);if(keyboardTab){keyboardTab.focus({preventScroll:true});keyboardTab=null;}});reveal(location.hash,!!location.hash);
tabs.forEach((t,i)=>t.addEventListener('keydown',e=>{let n=i;if(['ArrowDown','ArrowRight'].includes(e.key))n=(i+1)%tabs.length;else if(['ArrowUp','ArrowLeft'].includes(e.key))n=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;else if(e.key===' '){e.preventDefault();keyboardTab=t;go(t.hash);return;}else return;e.preventDefault();keyboardTab=tabs[n];tabs[n].focus({preventScroll:true});go(tabs[n].hash);}));
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();go(a.getAttribute('href'));if(a.matches('[role=tab]')&&innerWidth<=800){nav.hidden=true;menu.setAttribute('aria-expanded','false');}});
if(menu){menu.textContent='Zavihki';menu.setAttribute('aria-expanded',String(innerWidth>800));nav.hidden=innerWidth<=800;menu.addEventListener('click',()=>{nav.hidden=!nav.hidden;menu.setAttribute('aria-expanded',String(!nav.hidden));});window.addEventListener('resize',()=>{if(innerWidth>800){nav.hidden=false;menu.setAttribute('aria-expanded','true');}});}
const search=$('#report-search'),results=$('#report-results'),status=$('#report-search-status');
const entries=$$('.report-panel .section').map(el=>{const clone=el.cloneNode(true);clone.querySelectorAll('script,style,.related').forEach(x=>x.remove());return {id:el.id,title:el.querySelector('h2')?.textContent||el.id,panel:el.closest('.report-panel').dataset.label,text:norm(clone.textContent)};});
function searchAll(){const q=norm(search.value.trim());results.replaceChildren();results.hidden=!q;if(!q){status.textContent='Iščite po vseh zavihkih, tudi po trenutno skritih poglavjih.';return;}const found=entries.filter(x=>x.text.includes(q));for(const item of found){const a=document.createElement('a');a.href='#'+item.id;a.textContent=item.title;const small=document.createElement('small');small.textContent=item.panel;a.append(small);results.append(a);}status.textContent=found.length?`Najdena poglavja: ${found.length}. Izberite rezultat za odpiranje ustreznega zavihka.`:'Ni zadetkov. Poskusite krajši izraz ali drug zapis.';}
search.addEventListener('input',searchAll);search.addEventListener('keydown',e=>{if(e.key==='Enter'&&results.querySelector('a')){e.preventDefault();results.querySelector('a').click();}if(e.key==='Escape'){search.value='';searchAll();}});$('#clear-report-search').addEventListener('click',()=>{search.value='';searchAll();search.focus();});searchAll();
// Ločena pogleda uporabljata isto zbirko tras in iste obstoječe filtre.
const modes=$$('.route-modes button');function syncModes(){const pes=$('#poti-pes').checked,kolo=$('#poti-kolo').checked;const mode=pes&&kolo?'vse':pes?'pes':kolo?'kolo':'';modes.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));}
modes.forEach(b=>b.addEventListener('click',()=>{$('#poti-pes').checked=b.dataset.mode!=='kolo';$('#poti-kolo').checked=b.dataset.mode!=='pes';$('#poti-pes').dispatchEvent(new Event('change'));syncModes();}));['#poti-pes','#poti-kolo'].forEach(id=>$(id).addEventListener('change',syncModes));syncModes();
$('#poti-aed')?.addEventListener('change',e=>{$('#poti-aed-layer').style.display=e.target.checked?'':'none';});
// Razširi izpis poti samo s podatki iz istega ohranjenega podatkovnega zapisa.
const routeData=JSON.parse($('#poti-data').textContent);const routePanel=$('#poti .poti-panel');
new MutationObserver(()=>{if(routePanel.querySelector('.route-extra'))return;const sel=$('#poti .pot-route.selected');if(!sel)return;const r=routeData.poti.find(x=>x.id===Number(sel.dataset.id));if(!r||routePanel.querySelector('h3')?.textContent!==r.ime)return;const p=document.createElement('p');p.className='route-extra subtle';p.textContent=`Nadmorska višina točk GPX: ${r.visina_min??'ni podatka'}–${r.visina_max??'ni podatka'} m. To ni skupni vzpon. Izhodišče, podlaga, zahtevnost in dostopnost: niso dokumentirano preverjeni.`;routePanel.append(p);if(!r.izvirnik_na_voljo){const a=routePanel.querySelector('a[download]');if(a){a.removeAttribute('href');a.removeAttribute('download');a.setAttribute('aria-disabled','true');a.textContent='Izvirni GPX manjka v podedovanem arhivu';}}}).observe(routePanel,{childList:true});
const sportRows=$$('#sport-table tbody tr'),sportSearch=$('#sport-search'),sportType=$('#sport-type');
function filterSport(){const q=norm(sportSearch.value);let count=0;sportRows.forEach(r=>{r.hidden=!(norm(r.textContent).includes(q)&&(!sportType.value||r.dataset.sport===sportType.value));if(!r.hidden)count++;});$('#sport-count').textContent=`Prikazano: ${count} od ${sportRows.length} vrst dejavnosti. Objave ne potrjujejo današnjega urnika ali prostih mest.`;}
[sportSearch,sportType].forEach(el=>el.addEventListener('input',filterSport));filterSport();
// Dostopnost iz starega registra ne pomeni časovne dostopnosti.
const aedPanel=$('#aed-panel');new MutationObserver(()=>{if(aedPanel.querySelector('.aed-caution'))return;const p=document.createElement('p');p.className='aed-caution subtle';p.textContent='Notranja/zunanja namestitev in časovna dostopnost nista preverjeni. Oznaka javne dostopnosti izvira iz starega registra; ne potrjuje dostopa 24 ur na dan.';aedPanel.append(p);}).observe(aedPanel,{childList:true});
// Celoten dokument se tiska tudi po iskanju ali filtriranju.
let printState=null;
window.addEventListener('beforeprint',()=>{printState={details:$$('details').map(e=>[e,e.open]),hidden:$$('.report-panel [hidden]').map(e=>[e,e.hidden])};$$('details').forEach(e=>e.open=true);panels.forEach(e=>e.hidden=false);$$('.report-panel tr[hidden]').forEach(e=>e.hidden=false);});
window.addEventListener('afterprint',()=>{if(printState){printState.details.forEach(([e,v])=>e.open=v);printState.hidden.forEach(([e,v])=>e.hidden=v);}reveal(location.hash,false);filterSport();});
window.__reportReveal=hash=>reveal(hash,true);
})();
