(()=>{'use strict';
const normal=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const nav=document.querySelector('.sidebar nav'), menu=document.querySelector('.mobile-menu');
if(menu){if(innerWidth<=800)nav.hidden=true;menu.setAttribute('aria-expanded',String(!nav.hidden));menu.addEventListener('click',()=>{nav.hidden=!nav.hidden;menu.setAttribute('aria-expanded',String(!nav.hidden));});nav.addEventListener('click',e=>{if(e.target.closest('a')&&innerWidth<=800){nav.hidden=true;menu.setAttribute('aria-expanded','false');}});window.addEventListener('resize',()=>{if(innerWidth>800){nav.hidden=false;menu.setAttribute('aria-expanded','true');}});}
document.querySelectorAll('[data-print]').forEach(b=>b.addEventListener('click',()=>window.print()));
document.getElementById('backtop')?.addEventListener('click',()=>scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));
const meter=document.querySelector('.meter span');if(meter)window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;meter.style.width=(h>0?scrollY/h*100:0)+'%';},{passive:true});
if(nav&&'IntersectionObserver'in window){const ob=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){nav.querySelectorAll('a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id));}});},{rootMargin:'-10% 0px -70% 0px'});document.querySelectorAll('section[id]').forEach(s=>ob.observe(s));}
const dataNode=document.getElementById('chart-data');const data=dataNode?JSON.parse(dataNode.textContent):{};
document.querySelectorAll('.chart[data-key]').forEach(el=>{const d=data[el.dataset.key], slider=el.querySelector('input[type=range]'), output=el.querySelector('.readout'),line=el.querySelector('.cursor');if(!d||!slider)return;
const update=()=>{const i=Number(slider.value); output.textContent='Izdaja '+d.years[i]+' · '+d.series.map(s=>s.label+': '+(typeof s.values[i]==='number'?s.values[i].toLocaleString('sl-SI',{maximumFractionDigits:2}):'ni podatka')).join(' · '); if(line){const x=58+i/(d.years.length-1)*590;line.setAttribute('x1',x);line.setAttribute('x2',x);}slider.setAttribute('aria-valuetext','Izdaja '+d.years[i]);};slider.addEventListener('input',update);update();
el.querySelector('svg').addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*710;slider.value=Math.max(0,Math.min(d.years.length-1,Math.round((x-58)/590*(d.years.length-1))));update();});});
const search=document.getElementById('event-search');if(search){const aff=document.getElementById('aff-filter'),kind=document.getElementById('kind-filter'),theme=document.getElementById('theme-filter'),year=document.getElementById('year-filter');const rows=[...document.querySelectorAll('#events-table tbody tr')];
const filter=()=>{let shown=0;rows.forEach(r=>{const ok=(!aff.value||r.dataset.aff===aff.value)&&(!kind.value||r.dataset.kind===kind.value)&&(!theme.value||r.dataset.theme===theme.value)&&(!year.value||r.dataset.year===year.value)&&normal(r.textContent).includes(normal(search.value));r.hidden=!ok;if(ok)shown++;});document.getElementById('event-count').textContent='Prikazano '+shown+' od '+rows.length+' pregledanih objav.';document.getElementById('no-events').hidden=shown>0;};[search,aff,kind,theme,year].forEach(el=>el.addEventListener('input',filter));document.getElementById('reset-filters').addEventListener('click',()=>{search.value='';aff.value='Črnomelj';kind.value=theme.value=year.value='';filter();});filter();}
})();
