"""Preverjen imenik pomoči; lokalna izvedba ločena od možnosti sodelovanja."""
from pathlib import Path
import json,csv,re,html,shutil
P=Path(__file__).resolve().parent.parent;R=P
refs=json.loads((P/'drustva-viri.json').read_text(encoding='utf-8'))
refs['drustva-metuljcica']={'title':'Srečanja — Metuljčica','publisher':'Društvo Metuljčica','date':'b.d.','url':'https://www.metuljcica.si/srecanja/','local':'viri/splet/zdravstvo-20260920-drustva-metuljcica.md','access':'20. september 2026','note':'Uporabljen spletni izvleček; neposredni prenos vrne 403.'}
refs['drustva-ckz-imenik']['note']='Izdaja september 2025; pregledani zlasti natisnjeni str. 31, 33–34 in 39–40 (PDF 32, 34–35 in 40–41 po ničelni? Glej številčenje v lokalnem izvlečku).'
refs['drustva-ckz-imenik']['note']='Izdaja september 2025; natisnjene str. 31, 33–34 in 39–40, kar ustreza stranem PDF 33, 35–36 in 41–42 (šteto od 1). Kontakti iz imenika zahtevajo preverbo aktualnosti.'
(P/'drustva-viri.json').write_text(json.dumps(refs,ensure_ascii=False,indent=2),encoding='utf-8')
rows=[]
def add(name,scope,help,where,contact,conditions,keys):rows.append(dict(organizacija=name,dostopnost=scope,pomoc=help,kraj_termin=where,kontakt=contact,vkljucitev_omejitve=conditions,viri=keys))
add('Društvo Šola zdravja — Črnomelj in vaške skupine','Lokalna skupina objavljena','Redno skupinsko gibanje in druženje; možen partner za vzdrževanje gibalnih navad po obravnavi CKZ.','Črnomelj: vzpetina v parku Griček; ponedeljek–sobota ob 7.30, razen praznikov.','Lidija: 040 784 400; malesic.lidija@gmail.com','Termin je objavljen na strani skupine. Aktualno članarino, prilagoditve in možnost prvega obiska preveriti pri vodji; zneska iz 2024 ne prikazujemo kot veljavnega.',['sz','sz-skupine'])
add('Društvo koronarnih bolnikov Dolenjske in Bele krajine','Vadba v Črnomlju navedena','Strokovno vodena vseživljenjska rehabilitacijska vadba in podpora koronarnim bolnikom.','Zveza izrecno navaja Črnomelj med kraji vadbe; starejša objava društva potrjuje sodelovanje s CKZ v ZD.','info@koronarnodrustvo-dbk.si; za povezavo s skupino tudi CKZ Črnomelj.','Pred vključitvijo preveriti ustrezno skupino, aktualni termin in prispevek. Starega urnika ponedeljek/sreda ne potrjujemo za 2026.',['koronarni','koronarni-lokalno'])
add('Društvo diabetikov Metlika','Dostopno tudi iz Črnomlja','Izobraževanje o sladkorni bolezni, vrstniška podpora, pohodi in izmenjava izkušenj.','Objavljeno vpisno mesto: Društvo upokojencev Črnomelj, Ulica 21. oktobra 15; pisarna društva v Metliki.','slavo.prevalsek@siol.net','Vključuje tudi prebivalce širšega območja; dogovoriti se o članstvu, aktualnih srečanjih in stroških. Vpisno mesto ni diabetološka ambulanta.',['diabetiki','diabetiki-kontakt'])
add('Europa Donna Slovenija — skupina Bela krajina','Lokalna skupina objavljena','Podpora članicam ob zdravljenju raka dojk, skupnost, prilagojeni pohodi in druge aktivnosti.','Prvi torek v mesecu ob 18.00, Ljudska univerza Črnomelj, Kolodvorska cesta 32c. Objavljena je tudi sezonska joga.','Damjana Štefanič: 040 219 661; belakrajina@europadonna.si','Sprejemajo nove članice. Pred obiskom preveriti termin in pogoje posamezne aktivnosti; joga je navedena od oktobra do maja.',['donna'])
add('Metuljčica — skupina Črnomelj','Lokalna skupina objavljena','Samopomoč in izmenjava izkušenj ljudi z obolenji ščitnice.','Drugi torek v mesecu ob 18.00, sejna soba Občine Črnomelj.','Darinka Klemenčič: 040 251 649','Objavljen razpored nima datuma posodobitve. Termin preveriti; medsebojna podpora ne nadomešča zdravniškega spremljanja.',['metuljcica'])
add('Klub Zeleni Jurij — Združenje bolnikov s CVB','Lokalna skupina objavljena','Povezovanje in podporna skupnost bolnikov s cerebrovaskularno boleznijo, tudi po možganski kapi.','Zadnji četrtek v mesecu ob 17.00, Dom starejših občanov Črnomelj.','Sonja Imširović: 031 692 574; sonja.imsirovic@gmail.com','Pred prvim srečanjem potrditi termin, dostopnost in način vključitve; klub ni nadomestilo za predpisano rehabilitacijo.',['cvb'])
add('OZARA Črnomelj','Lokalno delo potrjeno; kontakt iz 2025','Pisarna za informiranje in svetovanje na področju duševnega zdravja. Lokalno sodelovanje potrjuje Knjižnica Črnomelj.','Črnomelj; aktualni naslov in urnik dogovoriti ob naročanju.','07 306 18 60; karmen.zunic@ozara.org','Kontakt je iz imenika CKZ 2025; neposredna podstran OZARE ni bila dostopna. Obseg sedanje ponudbe preveriti.',['ozara','ckz-imenik'])
add('Slovenska filantropija — Hiša Sadeži družbe Črnomelj','Lokalni center z objavami 2026','Brezplačne medgeneracijske dejavnosti, zdravo staranje, druženje in vključevanje prostovoljcev.','Železničarska cesta 5, Črnomelj; dejavnosti po mesečnem programu.','040 696 100; hisa-crnomelj@filantropija.org','Uradna stran navaja brezplačne aktivnosti; za nekatere je potrebna prijava. Gre za socialno in preventivno podporo.',['filantropija'])
add('RKS — Območno združenje Črnomelj','Lokalni izvajalec v imeniku CKZ','Krvodajalstvo, prva pomoč in humanitarna podpora.','Območje občin Črnomelj in Semič.','07 305 14 51; crnomelj.ozrk@siol.net','Podatki iz zbirnika CKZ, september 2025. Preveriti posamezni program; stroški tečajev niso preverjeni.',['ckz-imenik'])
add('Združenje multiple skleroze Slovenije — Dolenjska podružnica','Regionalno pokriva Črnomelj','Povezava bolnikov z MS z regionalno podružnico in podporno mrežo.','Podružnica izrecno vključuje Črnomelj, Metliko in Semič ter navaja poverjenico za Belo krajino.','Darinka Filipčič: 041 391 762; podružnica: 041 212 863','Pri poverjenici preveriti lokalna srečanja, programe in pogoje vključitve; spletna navedba območja ni potrdilo stalne ambulante.',['ms'])
add('Spominčica – Alzheimer Slovenija in lokalna demenci prijazna točka','Nacionalno združenje z lokalno povezavo','Informacije in podpora ob demenci; usposabljanje svojcev in lokalnih organizacij.','Ljudska univerza Črnomelj javno potrjuje demenci prijazno točko. LU je javni zavod, Spominčica pa združenje.','Spominčica: 01 256 51 11; info@spomincica.si','Za informacije se je mogoče obrniti na lokalno točko; za skupino svojcev ali novo usposabljanje dogovor s Spominčico. Točka ni diagnostična ambulanta ali stalna oskrba.',['spomincica','dpt'])
add('Slovensko društvo Hospic — Dolenjska, Posavje in Bela krajina','Regionalni odbor za območje','Spremljanje hudo bolnih in podpora svojcem ter žalujočim.','Regionalni odbor v Novem mestu; pomoč v konkretnem okolju se dogovori individualno.','051 454 845; dolenjska@hospic.si','Ob klicu preveriti možnost obiska in razpoložljivost podpore. Iz imenika ni mogoče obljubiti takojšnje ali 24-urne zdravstvene nege.',['hospic','hospic-regija'])
add('ŠENT — Dnevni center Novo mesto','Možen regionalni partner','Individualni razgovori, pomoč pri urejanju zadev in dejavnosti dnevnega centra za duševno zdravje.','Smrečnikova ulica 60, Novo mesto; uradno objavljen center, lokalna enota v Črnomlju ni potrjena.','030 767 702; amina.nur@sent.si','Individualni razgovori po predhodni najavi. Sprejem prebivalcev Črnomlja, prevoz in morebitne terenske dejavnosti je treba posebej dogovoriti.',['sent'])
add('Sožitje Bela krajina','Navedeno v lokalnem imeniku 2025','Kontakt za pomoč osebam z motnjami v duševnem razvoju in njihovim družinam.','Bela krajina; aktualni programi v Črnomlju niso dodatno potrjeni.','031 515 412; drustvo_sozitje@t-2.net','Predlagan partner za prilagojene programe; podrobni pogoji in zmogljivosti zahtevajo neposredno potrditev.',['ckz-imenik'])
add('Društvo invalidov Črnomelj','Navedeno v lokalnem imeniku 2025','Kontakt invalidske organizacije; možen partner pri dostopnosti in prilagojenem vključevanju.','Črnomelj; konkretnih zdravstvenih storitev s tem pregledom ne potrjujemo.','07 305 32 40; di.crnomelj@a1mail.si','Najprej preveriti sedanji program, dostopnost in članstvo. Vpis v imenik sam ne dokazuje izvajanja rehabilitacije.',['ckz-imenik'])
(P/'drustva-pomoc.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2),encoding='utf-8')
with (P/'drustva-pomoc.csv').open('w',encoding='utf-8-sig',newline='') as file:
 w=csv.DictWriter(file,fieldnames=list(rows[0]),delimiter=';');w.writeheader();w.writerows([{**r,'viri':', '.join(r['viri'])} for r in rows])
def cit(keys):return ''.join('{{cite:drustva-'+k+'}}' for k in keys)
body='''<section class="section" id="drustva" data-title="Društva in pomoč"><h2>Društva in podporna pomoč zunaj ambulante</h2><p class="intro">Pregled 15 društev, združenj oziroma njihovih lokalnih enot in povezanih točk, preverjen 20. septembra 2026. Vključuje redno gibanje, podporo pri kroničnih boleznih, duševnem zdravju, demenci in življenjskih stiskah.</p><div class="callout"><b>Koristna obstoječa osnova:</b> CKZ Črnomelj je že septembra 2025 izdal zbirnik <em>Povezani za zdravje</em> z lokalnimi kontakti. Smiselno ga je redno posodabljati in povezati z aktualnimi stranmi društev. To je dodatno potrjeno delo centra pri obveščanju; ocena dokumentiranega dela 3,4/5 ostaja, saj novi imenik ne meri zdravstvenih izidov. {{cite:drustva-ckz-imenik}}</div><h3>Šola zdravja: deset skupin v občini</h3><p>Uradni občinski seznam društva navaja Črnomelj, Dragatuš, Kanižarico, Tančo goro, Vinico, Špeharje, Zilje, Svibnik, Adlešiče in Majer. Zadnje tri skupine so navedene z letom ustanovitve 2025. Urnik na Gričku ne velja samodejno za ostale skupine. {{cite:drustva-sz-skupine}}</p><p class="subtle">»Objavljeno« pomeni navedbo v javnem viru, ne telefonske potrditve naslednjega termina. Pri organizacijah iz imenika 2025 je starost podatka posebej označena. Podporni programi dopolnjujejo zdravstveno obravnavo. Pogojev članstva, prispevkov in proste zmogljivosti ne domnevamo.</p><div class="table-scroll"><table><thead><tr><th>Organizacija / pomoč</th><th>Kje in kako do kontakta</th><th>Dostopnost in vključitev</th></tr></thead><tbody>'''
for r in rows:
 body+='<tr><td><b>'+html.escape(r['organizacija'])+'</b><p>'+html.escape(r['pomoc'])+'</p>'+cit(r['viri'])+'</td><td>'+html.escape(r['kraj_termin'])+'<p><b>'+html.escape(r['kontakt'])+'</b></p></td><td><span class="pill">'+html.escape(r['dostopnost'])+'</span><p>'+html.escape(r['vkljucitev_omejitve'])+'</p></td></tr>'
body+='''</tbody></table></div><p><a href="drustva-pomoc.csv" download>Prenesi imenik CSV</a></p><h3>Kako bi lahko sodelovali s CKZ in občino?</h3><div class="table-scroll"><table><thead><tr><th>Predlog / rok</th><th>Nosilci in sredstva</th><th>Korist in preverjanje</th></tr></thead><tbody><tr><td><b>0–12 mesecev:</b> preveriti kontakte ter uvesti pomoč pri prvem stiku po koncu obravnave CKZ; uporabnik sam izbere dejavnost.</td><td>CKZ in imenovani predstavniki društev. Planska ocena: 1–2 delovna dneva za prvi krog preverbe, nato mesečno vzdrževanje; obstoječe organizacijske ure.</td><td>Manj izgubljenih kontaktov. Merilo: aktualnost imenika in delež uporabnikov, ki so uspeli vzpostaviti stik; brez prenosa diagnoz društvom brez ustrezne podlage.</td></tr><tr><td><b>1–3 leta:</b> poskusno povezati redno gibanje, podporne skupine in dostopne prevoze v odročnejših krajih.</td><td>Občina, CKZ, Šola zdravja in druga zainteresirana društva. Obseg določiti s popisom potreb; možni občinski razpisi in redni viri izvajalcev, brez zagotovljenega financiranja.</td><td>Kontinuiteta in doseg zunaj mesta. Tveganje: preobremenitev prostovoljcev. Merilo: vztrajanje po 3/6 mesecih in geografski doseg.</td></tr><tr><td><b>3–10 let:</b> redno načrtovanje mreže skupaj z zdravstvenimi in socialnimi izvajalci.</td><td>Občina in izvajalci; večletni program po evalvaciji, z ločenim financiranjem strokovnih storitev in prostovoljskih dejavnosti.</td><td>Trajnost ob staranju prebivalstva. Merilo: nezadovoljene potrebe in uporabniška izkušnja; ne samo število dogodkov.</td></tr></tbody></table></div><p>To so predlogi sodelovanja, ne že sklenjeni dogovori. Za oceno uspešnosti posameznega društva potrebujemo doseg, obseg dela, vire in rezultate; sam seznam kontaktov ne zadošča za pošteno številčno oceno.</p></section>'''
(P/'drustva.html').write_text(body,encoding='utf-8')
order=[]
def md_cit(keys):
 numbers=[]
 for k in keys:
  k='drustva-'+k
  if k not in order:order.append(k)
  numbers.append('['+str(order.index(k)+1)+']')
 return ', '.join(numbers)
intro='CKZ je septembra 2025 že objavil lokalni zbirnik Povezani za zdravje. '+md_cit(['ckz-imenik'])+' Pregled dopolnjuje njegove kontakte z neposrednimi stranmi društev. Spletna navedba ni neodvisna potrditev kakovosti ali razpoložljivosti.'
wiki='# Društva in podporna mreža za zdravje v Črnomlju\n\n## Povzetek\n\n'+intro+'\n\n## Trenutno stanje\n\nPresek: 20. september 2026. Pregled 15 organizacij oziroma mrežnih povezav. Potrjene lokalne skupine, regionalna dostopnost in možnosti sodelovanja so ločene. LU Črnomelj je javni zavod in lokalna točka Spominčice; ni dodatno društvo.\n\n## Ključna dejstva\n\n| Organizacija in pomoč | Kraj in kontakt | Dostopnost / omejitve |\n| --- | --- | --- |\n'
for r in rows:wiki+='| **'+r['organizacija']+'**. '+r['pomoc']+' '+md_cit(r['viri'])+' | '+r['kraj_termin']+' '+r['kontakt']+' | **'+r['dostopnost']+'**. '+r['vkljucitev_omejitve']+' |\n'
wiki+='\nŠola zdravja navaja deset skupin: Črnomelj, Dragatuš, Kanižarica, Tanča gora, Vinica, Špeharji, Zilje, Svibnik, Adlešiči in Majer. Zadnje tri imajo leto ustanovitve 2025. '+md_cit(['sz-skupine'])+'\n\n## Viri\n\nPretežno primarni viri izvajalcev in CKZ. Zanesljivost je visoka za objavljene kontakte in obstoj navedbe, srednja za aktualno operativno razpoložljivost, ki ni bila potrjena po telefonu. Pri OZARI lokalno sodelovanje potrjuje tudi neposredni organizator dogodka — Knjižnica Črnomelj. Izvirniki so shranjeni v viri/splet; literatura vsebuje datum dostopa.\n\n## Identificirani problemi\n\nRazlična starost kontaktov, odsotnost jasnih pogojev vključitve in stroškov ter oddaljenost regionalnih programov. Obstoj podporne mreže ne dokazuje njene enakomerne dostopnosti po občini. Ne gre za ugotovitev, da društva ne delajo.\n\n## Kritična vprašanja\n\n'
qs=['Kdo v CKZ vzdržuje lokalni imenik in kako pogosto preverja kontakte?','Katera društva sprejemajo nove uporabnike in pod kakšnimi pogoji?','Kje so objavljeni prispevki in oprostitve plačila?','Kateri programi so dostopni gibalno ali senzorno oviranim?','Kako doseči prebivalce brez prevoza?','Koliko ljudi po obravnavi CKZ nadaljuje dejavnost v društvu?','Katere skupine so dejavne tudi med šolskimi počitnicami?','Kdo strokovno vodi prilagojeno vadbo?','Ali je mogoče organizirati skupino svojcev oseb z demenco bližje oddaljenim vasem?','Kako zagotoviti razbremenitev prostovoljcev in nadomeščanje vodij?','Kateri podatki o uspehu so zbrani brez nepotrebnega razkrivanja zdravstvenega stanja?','Kateri regionalni izvajalci dejansko lahko sprejmejo prebivalce Črnomlja?']
wiki+='\n'.join(f'{i}. {q}' for i,q in enumerate(qs,1))+'\n\n## Tveganja\n\nZastareli urniki, zamenjava društvene podpore z zdravljenjem in obljubljanje pomoči brez preverjene zmogljivosti. Iz imenika se ne sme sklepati, da je vsak program brezplačen, dostopen vsem ali neposredno prisoten v Črnomlju.\n\n## Možne rešitve\n\n| Rok | Ukrep, odgovorni in viri | Korist, tveganje, merilo |\n| --- | --- | --- |\n| 0–12 mesecev | CKZ in društva: prvi krog preverbe (ocena 1–2 delovna dneva), nato mesečno vzdrževanje v obstoječih urah. | Uspešni prvi stiki; tveganje zastarelosti; merilo delež preverjenih kontaktov in uspešnih vključitev. |\n| 1–3 leta | Občina, CKZ in društva: pilot povezovanja v odročnih krajih. Popis potreb pred finančno oceno; možni občinski razpisi in redni viri izvajalcev. | Kontinuiteta; tveganje preobremenitve; merilo geografski doseg in vztrajanje po 3/6 mesecih. |\n| 3–10 let | Večletno načrtovanje mreže po evalvaciji; občina in izvajalci, letni finančni in kadrovski načrt. | Trajnost; tveganje odvisnosti od posameznikov; merilo nezadovoljene potrebe in uporabniška izkušnja. |\n\n## Primerjave\n\nNi primerljivih podatkov za rangiranje društev ali občin. Različne vrste pomoči niso medsebojni nadomestki. ŠENT Novo mesto je potencialni regionalni partner; sprejem občanov in terenska izvedba nista potrjena.\n\n## Odprta vprašanja\n\nČlanarine, aktualni termini, čakalne dobe, prevozi, prilagoditve in merljivi izidi. Zato številčne ocene posameznim društvom niso dodeljene.\n\n## Povezane strani\n\n- [[sola-zdravja-crnomelj]]\n- [[pregled-drustev]]\n- [[../institutions/ckz-crnomelj]]\n- [[../../analysis/synthesis/starost-prebivalcev-crnomelj]]\n- [[../../analysis/synthesis/zdravstvo-preventiva-ckz-2026]]\n\n## Literatura\n\n'
for i,k in enumerate(order,1):
 r=refs[k];wiki+=f'[{i}] »{r["title"]},« {r["publisher"]}, {r["date"]}. [Na spletu]. Dostopno: {r["url"]}. [Dostopano: 20. september 2026]. Lokalna kopija: [[../../../{r["local"]}]]. {r["note"]}\n\n'
wiki+='## Zadnja posodobitev\n\n2026-09-20 — prvi preverjen pregled podporne mreže ob zdravstvenem poročilu.\n'
(R/'wiki/entities/associations/zdravstvena-podporna-mreza.md').write_text(wiki,encoding='utf-8')
sz='# Društvo Šola zdravja — skupine v Občini Črnomelj\n\n## Povzetek\n\nDruštvo ima v uradnem občinskem seznamu deset skupin. Za Črnomelj je objavljena jutranja vadba na vzpetini v mestnem parku Griček od ponedeljka do sobote ob 7.30, razen praznikov. [1], [2]\n\n## Ključna dejstva\n\n- Kontakt skupine Črnomelj: Lidija, 040 784 400, malesic.lidija@gmail.com. [1]\n- Skupine: Črnomelj in Dragatuš (2013), Kanižarica (2014), Tanča gora (2018), Vinica (2019), Špeharji (2023), Zilje (2024), Svibnik, Adlešiči in Majer (2025). [2]\n- Datumi pomenijo navedena leta ustanovitve, ne preverbe neprekinjenega delovanja. Aktualne termine vaških skupin je treba preveriti ločeno.\n\n## Pomen za lokalno zdravje\n\nMožen partner za redno gibanje in druženje po obravnavi CKZ. To je priporočilo za povezovanje, ne dokaz že vzpostavljene napotne poti ali merljivega zdravstvenega učinka. Članarina, dostopnost in prilagoditve niso potrjene za 2026.\n\n## Povezane strani\n\n- [[zdravstvena-podporna-mreza]]\n- [[../institutions/ckz-crnomelj]]\n\n## Literatura\n\n'
for i,k in enumerate(['drustva-sz','drustva-sz-skupine'],1):
 r=refs[k];sz+=f'[{i}] »{r["title"]},« Društvo Šola zdravja, b.d. [Na spletu]. Dostopno: {r["url"]}. [Dostopano: 20. september 2026]. Lokalna kopija: [[../../../{r["local"]}]].\n\n'
sz+='## Zadnja posodobitev\n\n2026-09-20.\n';(R/'wiki/entities/associations/sola-zdravja-crnomelj.md').write_text(sz,encoding='utf-8')
print('Pripravljeno:',len(rows),'organizacij;',len(order),'virov v wikiju.')
