"""Iz uradnih odgovorov SURS izdela preverljive demografske priloge."""
from pathlib import Path
import json,csv,re,html
P=Path(__file__).resolve().parent.parent;R=P
A=json.loads((P/'surs-05C4003S-podatki.json').read_text(encoding='utf-8'))
B=json.loads((P/'surs-05C4008S-podatki.json').read_text(encoding='utf-8'))
a={tuple(d['key']):int(d['values'][0]) for d in A['data']}
b={tuple(d['key']):float(d['values'][0]) for d in B['data']}
def count(y,lo=0,hi=85,area='017'):return sum(a[area,f'{y}H1',str(i)] for i in range(lo,hi+1))
def metric(y,k,area='017'):return b[area,f'{y}H1','0',str(k)]
def f(n,dec=0):return f'{n:,.{dec}f}'.replace(',',' ').replace('.',',')
discrepancies=[]
for area in ['017','0']:
    for y in range(2008,2027):
        if count(y,area=area)!=a[area,f'{y}H1','999']:
            discrepancies.append({'obmocje':area,'leto':y,'skupaj':a[area,f'{y}H1','999'],'vsota_starosti':count(y,area=area)})
            assert (area,y)==('0',2008),discrepancies
        assert abs(100*count(y,65,85,area)/count(y,area=area)-metric(y,5,area))<=.051
(P/'starost-preverjanje.json').write_text(json.dumps({'preverjene_vsote':38,'ujemanja':38-len(discrepancies),'neskladja':discrepancies,'opomba':'Razlika 2 oseb za Slovenijo 2008 je že v izvornem odgovoru; razlog ni ugotovljen. Glavni prikaz 2011–2026 tega leta ne vključuje.'},ensure_ascii=False,indent=2),encoding='utf-8')
years=list(range(2011,2027));groups=[(i,min(i+4,85)) for i in range(0,85,5)]+[(85,85)]
annual=[[y,count(y),count(y,0,14),count(y,15,64),count(y,65,85),count(y,80,85),metric(y,1),metric(y,1,'0'),metric(y,2)] for y in years]
headers=['Leto (1. 1.)','Skupaj','0–14 let','15–64 let','65+ let','80+ let¹','Starost Črnomelj','Starost Slovenija','Indeks staranja']
def table(headers,rows):return '<div class="table-scroll"><table><thead><tr>'+''.join('<th>'+h+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(v)+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'
display=[[str(row[0])]+[f(v,1 if i>=6 else 0) for i,v in enumerate(row[1:],1)] for row in annual]
agegroups=[['85 let in več' if lo==85 else f'{lo}–{hi} let',f(count(2026,lo,hi)),f(100*count(2026,lo,hi)/count(2026),1)] for lo,hi in groups]
single=[['85 let in več' if i==85 else str(i),f(a['017','2026H1',str(i)])] for i in range(86)]
with (P/'starost-po-letih.csv').open('w',encoding='utf-8-sig',newline='') as file:
    w=csv.writer(file,delimiter=';');w.writerow(headers);w.writerows(annual)
with (P/'starost-posamezna-leta-2026.csv').open('w',encoding='utf-8-sig',newline='') as file:
    w=csv.writer(file,delimiter=';');w.writerow(['Starost na 1. 1. 2026','Število prebivalcev']);w.writerows([['85+' if i==85 else str(i),a['017','2026H1',str(i)]] for i in range(86)])
svg='<svg style="width:100%;height:auto" viewBox="0 0 710 280" role="img" aria-label="Povprečna starost Črnomlja in Slovenije od 2011 do 2026"><title>Povprečna starost na 1. januar</title>'
for age in range(40,48):
    yy=230-(age-40)*28
    svg+=f'<line x1="50" y1="{yy}" x2="660" y2="{yy}" stroke="#dce3d9"/><text x="15" y="{yy+4}" fill="#526862" font-size="12">{age}</text>'
for area,color,name in [('017','#17695b','Črnomelj'),('0','#4569a3','Slovenija')]:
    points=' '.join(f'{50+i*610/15},{230-(metric(y,1,area)-40)*28}' for i,y in enumerate(years))
    svg+=f'<polyline points="{points}" fill="none" stroke="{color}" stroke-width="3"/>'
    for i,y in enumerate(years):svg+=f'<circle cx="{50+i*610/15}" cy="{230-(metric(y,1,area)-40)*28}" r="3" fill="{color}"><title>{name}, {y}: {f(metric(y,1,area),1)} leta</title></circle>'
for i,y in enumerate(years):
    if y in [2011,2016,2021,2026]:svg+=f'<text x="{50+i*610/15}" y="255" text-anchor="middle" fill="#526862" font-size="12">{y}</text>'
svg+='</svg>'
total=count(2026);n65=count(2026,65);n14=count(2026,0,14);n80=count(2026,80)
summary=f'Na 1. januar 2026 ima Občina Črnomelj **{f(total)} prebivalcev**. Povprečna starost je **45,9 leta**, v Sloveniji 44,6 leta. Prebivalcev, starih 65 let ali več, je **{f(n65)} (25,5 %)**, otrok do 14 let **{f(n14)} (14,5 %)**. Indeks staranja 176,2 pomeni približno 176 starejših na 100 otrok. [1], [2]'
intro=f'Na <b>1. januar 2026</b> ima občina <b>{f(total)} prebivalcev</b>. Povprečna starost je <b>45,9 leta</b>, kar je 1,3 leta nad slovenskim povprečjem (44,6). Delež starih 65 let ali več dosega <b>25,5 %</b>, v Sloveniji 22,5 %. {{{{cite:surs-starost}}}}{{{{cite:surs-kazalniki}}}}'
interpret=f'Od začetka 2011 do začetka 2026 se je število prebivalcev zmanjšalo za {f(count(2011)-total)} (3,7 %), število starih 65+ pa povečalo z 2.420 na 3.616 (+49,4 %). Število starih 15–64 let je upadlo z 10.266 na 8.502 (−17,2 %). Otrok 0–14 let je bilo 2.031, zdaj jih je 2.052; po letu 2021 se je njihovo število zmanjšalo. To opisuje spremembo sestave, ne dokazuje posameznega vzroka selitev ali staranja. {{{{cite:surs-starost}}}}'
method='Oba spola skupaj; prebivalci celotne občine, ne samo mesta Črnomelj ali celotnega območja ZD. H1 pomeni stanje na 1. januar, ne letnega povprečja. Najnovejše stanje je 1. 1. 2026, objavljeno 18. 5. 2026. Povprečno starost uporabljamo neposredno iz SURS; ne izračunavamo je iz skupine 85+. Pri občinah SURS od 2011 uporablja enoletne starostne skupine, zato je glavni trend prikazan od 2011. Celotni prenos števil je za 2008–2026. ¹ Skupina 80+ je že vključena v 65+; teh stolpcev se ne sešteva. {{cite:surs-metoda}}'
meaning='Več starejših pomeni večjo potrebo po dostopni obravnavi kroničnih bolezni, preprečevanju padcev, prevozih in pomoči na domu; to je načrtovalska interpretacija, ne izmerjena lokalna potreba po določenem številu mest. Delež 80+ je leta 2026 5,8 % v občini in 5,8 % v Sloveniji (pri objavi na eno decimalko). Podobnost pri najstarejših torej ne pomeni enake povprečne starosti ali deleža 65+. {{cite:surs-kazalniki}} Starostno standardiziranih zdravstvenih stopenj tudi po tej dopolnitvi ne pojasnjujemo zgolj s starejšim prebivalstvom. {{cite:opisi}}'
body=f'<section class="section" id="starost" data-title="Starost prebivalcev"><h2>Starost prebivalcev in staranje občine</h2><p class="intro">{intro}</p><div class="callout">{interpret}</div><figure class="demografski-graf" style="margin:20px 0;background:white;padding:18px;border:1px solid #dce3d9;border-radius:10px"><figcaption><b>Povprečna starost, 2011–2026</b><br><span class="subtle">Zelena: Črnomelj · modra: Slovenija · stanje na 1. januar · v letih</span></figcaption>{svg}<p class="subtle">Vir: SURS; vse vrednosti so tudi v spodnji tabeli. {{{{cite:surs-kazalniki}}}}</p></figure><h3>Prebivalstvo in starostne skupine po letih</h3>'+table(headers,display)+f'<p class="subtle">{method}</p><p><a href="starost-po-letih.csv" download>Prenesi letno tabelo CSV</a> · <a href="surs-05C4003S.csv" download>Vse starosti, 2008–2026, Črnomelj in Slovenija</a></p><h3>Koliko ljudi je v posamezni starostni skupini?</h3><p>Stanje na 1. januar 2026. Zadnja skupina je odprta (85 let in več). {{{{cite:surs-starost}}}}</p>'+table(['Starost','Prebivalci','Delež (%)'],agegroups)+'<details><summary>Odpri celotno tabelo: posamezna leta starosti 0–84 in 85+</summary>'+table(['Starost (leta)','Število prebivalcev'],single)+'</details><p><a href="starost-posamezna-leta-2026.csv" download>Prenesi tabelo po posameznih letih starosti</a></p><h3>Kaj to pomeni za zdravstveno poročilo?</h3><p>'+meaning+'</p></section>'
(P/'demografija.html').write_text(body,encoding='utf-8')
refs={}
for key,tableid,title in [('surs-starost','05C4003S','Prebivalstvo po starosti, občine, Slovenija, polletno'),('surs-kazalniki','05C4008S','Prebivalstvo — izbrani kazalniki, občine, Slovenija, polletno'),('surs-metoda','05C4008S','Prebivalstvo — izbrani kazalniki: metodološka pojasnila')]:
    refs[key]={'title':title,'publisher':'Statistični urad Republike Slovenije','date':'18. maj 2026','url':f'https://pxweb.stat.si/SiStatData/pxweb/sl/Data/-/{tableid}.px','local':f'viri/splet/zdravstvo-20260919-surs-{tableid.lower()}.md' if key!='surs-metoda' else 'viri/splet/zdravstvo-20260919-surs-starost-metodologija.md','note':'Poizvedba: Slovenija in Črnomelj, H1 2008–2026, oba spola skupaj. Podrobni izvoz ob poročilu.'}
(P/'starost-viri.json').write_text(json.dumps(refs,ensure_ascii=False,indent=2),encoding='utf-8')
def mdtable(headers,rows):return '| '+' | '.join(headers)+' |\n| '+' | '.join('---' for _ in headers)+' |\n'+'\n'.join('| '+' | '.join(map(str,row))+' |' for row in rows)
wiki='# Starostna sestava prebivalcev Občine Črnomelj\n\n## Povzetek\n\n'+summary+'\n\n## Trenutno stanje\n\n'+re.sub(r'\{\{cite:[^}]+\}\}','[3]',method)+'\n\n## Ključna dejstva\n\n'+re.sub(r'\{\{cite:[^}]+\}\}','[1]',interpret)+'\n\n'+mdtable(headers,display)+'\n\n### Starostne skupine na 1. januar 2026\n\n'+mdtable(['Starost','Prebivalci','Delež (%)'],agegroups)+'\n\nPodatki v tabelah: [1], [2]. Celotna enoletna razdelitev 0–84 in 85+ ter CSV so v [poročilu](../../../porocilo.html#starost).\n\n## Viri\n\nSURS, primarni uradni statistični vir; visoka zanesljivost za stanje prebivalstva. Ohranjen izvirni odgovor API, metapodatki, poizvedba ter CSV. Vsota 86 starostnih razredov se ujema s skupnim prebivalstvom v 37 od 38 kombinacij območja in leta. Za Slovenijo 2008 je že v izvirniku razlika 2 oseb (skupaj 2.025.866, vsota 2.025.864); razlog ni ugotovljen. Glavni prikaz 2011–2026 nima tega neskladja. Zaokroženi deleži preverjeni proti uradnim kazalnikom.\n\n## Identificirani problemi\n\nManj prebivalcev v starosti 15–64 let ob več starejših pomeni izziv zmogljivosti oskrbe, vendar sama struktura ne meri zaposlitve, bolezni ali odvisnosti posameznika. Povprečje občine skriva razlike med naselji. Iz prečnega prereza po starosti ni mogoče ugotoviti vzroka odseljevanja.\n\n## Kritična vprašanja\n\n'
questions=['Kolikšne so razlike v deležu 65+ med naselji?','Kje prebivajo starejši z omejenimi prevozi do ambulante?','Koliko starejših dejansko potrebuje pomoč na domu in koliko jih čaka?','Kako se bo obseg patronaže prilagodil večji skupini 65+?','Kolikšen del spremembe prebivalstva pojasnijo rojstva, smrti in selitve?','Kako se starostna sestava priseljenih razlikuje od odseljenih?','Ali ima CKZ podatke o dosegu po starosti in kraju?','Koliko stanovanj je prilagojenih funkcionalno oviranim uporabnikom?','Kakšna je razpoložljivost družinskih oskrbovalcev?','Kakšni so trije scenariji potreb po kadru in oskrbi za 2030–2035?']
wiki+='\n'.join(f'{i}. {q}' for i,q in enumerate(questions,1))+'\n\n## Tveganja\n\nZamenjava 65+ in 80+, seštevanje prekrivajočih se skupin, mešanje 1. januarja z 1. julijem in pripisovanje starostno standardizirane umrljivosti sami starosti. Število oseb 15–64 ne pomeni števila zaposlenih. Prihodnje potrebe ostajajo scenariji, ne napoved iz teh podatkov.\n\n## Možne rešitve\n\n'+mdtable(['Rok','Ukrep in odgovorni','Viri in financiranje','Korist, tveganje, merilo'],[['0–12 mesecev','Občina, ZD in socialni izvajalci: združiti javne agregate po starosti in kraju ter popisati čakalne dobe.','Predlog: 1–2 človekova meseca analitičnega dela; redna sredstva ustanov, brez potrjenega novega proračuna.','Boljša ocena potreb; tveganje nezdružljivih evidenc; merilo objavljena izhodiščna analiza.'],['1–3 leta','ZD, CKZ in občina: ciljno širiti preventivo padcev, dostopne prevoze in obravnavo kroničnih stanj glede na popis potreb.','Obseg kadra in stroškov šele po analizi; redna zdravstvena/socialna sredstva in občinski proračun v okviru pristojnosti.','Dostopnost; tveganje kadrovskih vrzeli; merilo doseg, čakanje in funkcionalni izidi.'],['3–10 let','Občina in izvajalci: trije scenariji zmogljivosti pomoči na domu, kadrov in prilagojenih stanovanj.','Posebna študija potreb in investicijski program; možni nacionalni in evropski razpisi ob preverbi upravičenosti.','Prilagajanje potrebam; tveganje napačnih projekcij; merilo letna revizija scenarijev in nezadovoljene potrebe.']])+'\n\n## Primerjave\n\nLeta 2026: Črnomelj 45,9 proti 44,6 leta; delež 65+ 25,5 proti 22,5 %; indeks staranja 176,2 proti 158,6. Delež 80+ je 5,8 proti 5,8 % (objavljeno na eno decimalko). Primerjave uporabljajo isto opredelitev in datum. [2]\n\n## Odprta vprašanja\n\nRazlike med naselji, selitvena struktura in prihodnje potrebe po storitvah. Iz starostne sestave ne ocenjujemo kakovosti CKZ ali občinskega upravljanja z oceno 1–5.\n\n## Povezane strani\n\n- [[../../topics/social-affairs/zdravje-obcina-nijz-trendi]]\n- [[zdravstvo-preventiva-ckz-2026]]\n- [[pregled-za-kandidata]]\n\n## Literatura\n\n'
for i,(key,r) in enumerate(refs.items(),1):wiki+=f'[{i}] »{r["title"]},« SURS, 18. maj 2026. [Na spletu]. Dostopno: {r["url"]}. [Dostopano: 19. september 2026]. Lokalna kopija: [[../../../{r["local"]}]].\n\n'
wiki+='## Zadnja posodobitev\n\n2026-09-19 — neposredni zajem in preverba tabel SURS.\n'
(R/'wiki/analysis/synthesis/starost-prebivalcev-crnomelj.md').write_text(wiki,encoding='utf-8')
print(summary);print('Kontrole: 37 vsot se ujema; Slovenija 2008 ima dokumentirano razliko 2 oseb. Vsi deleži 65+ preverjeni.')
