(()=>{'use strict';
const root=document.getElementById('poti'),data=JSON.parse(document.getElementById('poti-data').textContent),svg=root.querySelector('svg'),panel=root.querySelector('.poti-panel');
const routes=[...root.querySelectorAll('.pot-route')],rows=[...root.querySelectorAll('#poti-tabela tbody tr')],places=[...root.querySelectorAll('.pot-place')];
const controls={pes:root.querySelector('#poti-pes'),kolo:root.querySelector('#poti-kolo'),zunaj:root.querySelector('#poti-zunaj'),kraji:root.querySelector('#poti-kraji'),pas:root.querySelector('#poti-pas'),search:root.querySelector('#poti-search')};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n).toLocaleString('sl-SI',{minimumFractionDigits:1,maximumFractionDigits:1});
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
let view=[...data.obcina],selected=null,drag=null,moved=false;
function draw(){svg.setAttribute('viewBox',view.join(' '));const pixel=view[2]/Math.max(svg.clientWidth,300);svg.querySelectorAll('.pot-place circle').forEach(c=>c.setAttribute('r',4*pixel));svg.querySelectorAll('.pot-label').forEach(t=>t.style.fontSize=(12*pixel)+'px');}
function setView(v){view=[...v];draw();}
function zoom(f,cx=view[0]+view[2]/2,cy=view[1]+view[3]/2){const w=Math.min(data.vse[2]*1.5,Math.max(data.obcina[2]/35,view[2]*f)),h=w*view[3]/view[2];view=[cx-(cx-view[0])*w/view[2],cy-(cy-view[1])*h/view[3],w,h];draw();}
function coords(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());}
function visible(r){return (r.vrsta==='pohodnistvo'?controls.pes.checked:controls.kolo.checked)&&(controls.zunaj.checked||r.v_obcini)&&norm(r.ime).includes(norm(controls.search.value));}
function apply(){let n=0;routes.forEach(g=>{const r=data.poti[+g.dataset.id],show=visible(r);g.style.display=show?'':'none';if(show)n++;g.querySelectorAll('.pot-outside').forEach(p=>p.style.display=controls.zunaj.checked?'':'none');});rows.forEach(r=>r.hidden=!visible(data.poti[+r.dataset.id]));places.forEach(p=>p.style.display=controls.kraji.checked?'':'none');root.querySelectorAll('.pot-buffer').forEach(p=>p.style.display=p.dataset.radius===controls.pas.value?'':'none');root.querySelector('#poti-count').textContent=`Prikaz: ${n} od ${data.poti.length} tras. Analiza spodaj vedno obravnava celotno zbirko.`;if(selected!==null&&!visible(data.poti[selected])){panel.innerHTML='<h3>Trasa je skrita s filtrom</h3><p>Spremenite filter ali izberite drugo traso.</p>';selected=null;}}
function pick(id,focus=false){const r=data.poti[id];selected=id;routes.forEach(g=>g.classList.toggle('selected',+g.dataset.id===id));rows.forEach(g=>g.classList.toggle('selected',+g.dataset.id===id));panel.innerHTML=`<h3>${esc(r.ime)}</h3><p><span class="pot-badge ${r.vrsta}">${r.vrsta==='pohodnistvo'?'Pohodniška sled':'Kolesarska sled'}</span></p><dl><dt>Celotna trasa GPX</dt><dd>${fmt(r.km)} km</dd><dt>Znotraj občine</dt><dd>${fmt(r.km_v_obcini)} km (${fmt(r.delez_v_obcini)} %)</dd><dt>Segmenti / točke</dt><dd>${r.segmenti} / ${r.tocke.toLocaleString('sl-SI')}</dd><dt>Največji razmik točk</dt><dd>${Math.round(r.max_razmik_m)} m</dd></dl><p class="subtle">Vrsta iz izvorne mape; prikazana dolžina je izračun iz koordinat. Prehodnost, prometna varnost, podlaga in dostopnost niso potrjene.</p><a class="btn" href="${encodeURI(r.datoteka)}" download>Prenesi izvirni GPX</a>`;
if(focus){if(!r.v_obcini){controls.zunaj.checked=true;apply();}setView(controls.zunaj.checked?r.bbox:r.bbox_inside);}}
root.querySelector('.poti-zoom').addEventListener('click',e=>{const action=e.target.closest('button')?.dataset.action;if(action==='in')zoom(.65);if(action==='out')zoom(1/.65);if(action==='reset')setView(data.obcina);if(action==='all'){controls.zunaj.checked=true;apply();setView(data.vse);}});
svg.addEventListener('click',e=>{if(moved){moved=false;return;}const g=e.target.closest('.pot-route'),n=e.target.closest('.pot-place');if(g)pick(+g.dataset.id);else if(n){const r=data.naselja[+n.dataset.id];selected=null;panel.innerHTML=`<h3>${esc(r.ime)}</h3><p>Zračna razdalja od točke kraja OSM do najbližjega odseka znotraj občine:</p><dl><dt>Pohodniška sled</dt><dd>${fmt(r.pohodnistvo_m/1000)} km</dd><dt>Kolesarska sled</dt><dd>${fmt(r.kolesarstvo_m/1000)} km</dd></dl><p>Najbližja trasa: <b>${esc(data.poti[r.najblizja_pot_id].ime)}</b>.</p><p class="subtle">To ni razdalja po cesti ali pot do urejenega vstopa. Ne predstavlja razdalje vseh prebivalcev kraja.</p>`;}});
svg.addEventListener('keydown',e=>{const target=e.target.closest('.pot-route,.pot-place');if(target&&(e.key==='Enter'||e.key===' ')){e.preventDefault();target.dispatchEvent(new MouseEvent('click',{bubbles:true}));return;}if(e.key==='+'||e.key==='='){e.preventDefault();zoom(.65);}if(e.key==='-'){e.preventDefault();zoom(1/.65);}if(e.key==='Home'){e.preventDefault();setView(data.obcina);}const shifts={ArrowLeft:[-.15,0],ArrowRight:[.15,0],ArrowUp:[0,-.15],ArrowDown:[0,.15]};if(shifts[e.key]){e.preventDefault();view[0]+=view[2]*shifts[e.key][0];view[1]+=view[3]*shifts[e.key][1];draw();}});
svg.addEventListener('dblclick',e=>{const p=coords(e);zoom(.55,p.x,p.y);});
svg.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={p:coords(e),view:[...view],x:e.clientX,y:e.clientY};moved=false;});
window.addEventListener('pointermove',e=>{if(!drag)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5)moved=true;if(moved){const p=coords(e);view[0]+=drag.p.x-p.x;view[1]+=drag.p.y-p.y;draw();}});
window.addEventListener('pointerup',()=>{drag=null;});window.addEventListener('pointercancel',()=>{drag=null;});
rows.forEach(row=>row.querySelector('button').addEventListener('click',()=>{pick(+row.dataset.id,true);root.querySelector('.poti-layout').scrollIntoView({behavior:'smooth',block:'start'});}));
Object.values(controls).forEach(el=>el.addEventListener(el.type==='search'?'input':'change',apply));
let saved=null;
window.addEventListener('beforeprint',()=>{saved={view:[...view],pes:controls.pes.checked,kolo:controls.kolo.checked,zunaj:controls.zunaj.checked,kraji:controls.kraji.checked,pas:controls.pas.value,search:controls.search.value};controls.pes.checked=controls.kolo.checked=controls.zunaj.checked=controls.kraji.checked=true;controls.pas.value='';controls.search.value='';apply();setView(data.obcina);});
window.addEventListener('afterprint',()=>{if(!saved)return;['pes','kolo','zunaj','kraji'].forEach(k=>controls[k].checked=saved[k]);controls.pas.value=saved.pas;controls.search.value=saved.search;apply();setView(saved.view);saved=null;});
window.addEventListener('resize',draw);apply();draw();
})();
